packages:
  - packages/*

catalog:
  eslint: ^9.36
  prettier: ^3.6
  typescript: ^5.8

ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - unrs-resolver

linkWorkspacePackages: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@ktam/*"

publicHoistPattern:
  - "@typescript-eslint/parser"
  - eslint-plugin-jsx-a11y

publishBranch: main

savePrefix: ""

saveWorkspaceProtocol: rolling
