packages:
  - packages/*

blockExoticSubdeps: true

catalog:
  eslint: ^9.39
  prettier: ^3.8
  typescript: ^5.9.3

ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver

linkWorkspacePackages: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@ktam/*"

publishBranch: main

savePrefix: ""

saveWorkspaceProtocol: rolling

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080 # 1 week

publicHoistPattern:
  - "@typescript-eslint/parser"
  - "eslint-plugin-jsx-a11y"
