packages:
  - packages/*

catalog:
  eslint: ^9.39.4
  prettier: ^3.8.4
  typescript: ^5.9.3

dedupePeers: true

minimumReleaseAge: 2880 # 48 hours
minimumReleaseAgeExclude:
  - '@ktam/*'

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 1 week

publicHoistPattern:
  - '@typescript-eslint/parser'
  - 'eslint-plugin-jsx-a11y'

publishBranch: main

savePrefix: ''
saveWorkspaceProtocol: rolling

allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false
