packages:
  - packages/*

blockExoticSubdeps: true

catalog:
  eslint: ^9.39.4
  prettier: ^3.8.2
  typescript: ^5.9

dedupePeers: true

ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver

linkWorkspacePackages: true

minimumReleaseAge: 2880 # 48 hours

minimumReleaseAgeExclude:
  - "@ktam/*"

publicHoistPattern:
  - "@typescript-eslint/parser"
  - "eslint-plugin-jsx-a11y"

publishBranch: main

savePrefix: ""

saveWorkspaceProtocol: rolling

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080 # 1 week
