name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v5
      - name: Set up pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - name: Set up Node.JS
        uses: actions/setup-node@v5

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Project
        run: pnpm lint
      - name: Check Code Formatting
        run: pnpm prettier:check
      - name: Typecheck Project
        run: pnpm typecheck

      # If you have a monorepo, you can add the following steps to the job:

      - name: Check Dependency Version Consistency
        run: pnpm check-dependency-version-consistency .
      - name: Check for Duplicated Dependencies
        run: pnpm dedupe --check
